brand_customer_index:
    path:     /
    defaults: { _controller: "B2bBundle:Customer:indexForBrand" }
    methods:  GET

brand_customer_show:
    path:     /{id}/show
    defaults: { _controller: "B2bBundle:Customer:show" }
    methods:  GET

brand_customer_new:
    path:     /new
    defaults: { _controller: "B2bBundle:Customer:new" }
    methods:  [GET, POST]

brand_customer_edit:
    path:     /{id}/edit
    defaults: { _controller: "B2bBundle:Customer:edit" }
    methods:  [GET, POST]

brand_customer_delete:
    path:     /{id}/delete
    defaults: { _controller: "B2bBundle:Customer:delete" }
    methods:  DELETE