salesman_index:
    path:     /
    defaults: { _controller: "B2bBundle:Salesman:indexForBrand" }
    methods:  GET

salesman_new:
    path:     /new
    defaults: { _controller: "B2bBundle:Salesman:new" }
    methods:  [GET,POST]

salesman_show:
    path:     /{id}/show
    defaults: { _controller: "B2bBundle:Salesman:show" }
    methods:  [GET,POST]

salesman_edit:
    path:     /{id}/edit
    defaults: { _controller: "B2bBundle:Salesman:edit" }
    methods:  [GET,POST]

salesman_remove:
    path:     /{id}/remove
    defaults: { _controller: "B2bBundle:Salesman:remove" }
    methods:  [GET,POST]