<?php

namespace B2bBundle\Repository;

/**
 * AllowedColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllowedColorRepository extends \Doctrine\ORM\EntityRepository
{
}
