<?php

namespace B2bBundle\Repository;

/**
 * AllowedSizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllowedSizeRepository extends \Doctrine\ORM\EntityRepository {
    public function findForProduct($product) {
        return $this->createQueryBuilder('a')
            ->where('a.product = :product_id')
            ->setParameter('product_id', $product->getId())
            ->innerJoin('a.size', 's')
            ->orderBy('s.rank', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
