<?php

namespace B2bBundle\Repository;

/**
 * AvailabilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvailabilityRepository extends \Doctrine\ORM\EntityRepository {
    public function findOrderedSizeQuantities($availability) {
        return $this->createQueryBuilder('a')
            ->where('a.id = :availability_id')
            ->setParameter('availability_id', $availability)
            ->orderBy('a.size.rank', 'ASC')
            ->getQuery()
            ->getResult()
            ;
    }
}
