<?php

namespace B2bBundle\Repository;

/**
 * CartCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartCategoryRepository extends \Doctrine\ORM\EntityRepository {
    public function findCategory($cartCollection, $category) {
        $QueryBuilder = $this->createQueryBuilder('c')
            ->where('c.cartCollection = :cart_collection_id')
            ->andWhere('c.category = :category_id')
            ->setParameters(array('cart_collection_id' => $cartCollection, 'category_id' => $category));
        return $QueryBuilder->getQuery()->getResult();
    }
}