<?php

namespace B2bBundle\Repository;

/**
 * CartCollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartCollectionRepository extends \Doctrine\ORM\EntityRepository {
    public function findCollection($cart, $collection) {
        $QueryBuilder = $this->createQueryBuilder('c')
            ->where('c.cart = :cart_id')
            ->andWhere('c.collection = :collection_id')
            ->setParameters(array('cart_id' => $cart, 'collection_id' => $collection));
        return $QueryBuilder->getQuery()->getResult();
    }
}