<?php

namespace B2bBundle\Repository;

/**
 * CartRowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRowRepository extends \Doctrine\ORM\EntityRepository {
    public function findCartRow($category, $product, $color) {
        $QueryBuilder = $this->createQueryBuilder('c')
            ->where('c.cartCategory = :category_id')
            ->andWhere('c.product = :product_id')
            ->andWhere('c.color = :color_id')
            ->setParameters(array('category_id' => $category, 'product_id' => $product, 'color_id' => $color));
        return $QueryBuilder->getQuery()->getResult();
    }

    public function searchFromCommand($command, $text) {
        $QueryBuilder = $this->createQueryBuilder('row')
            ->innerJoin('row.product', 'p')
            ->innerJoin('row.cartCategory', 'cat')
            ->innerJoin('cat.cartCollection', 'collection')
            ->innerJoin('B2bBundle:Command', 'command', 'WITH')
            ->where(':command_id = command')
            //->andWhere('row MEMBER OF cart.cartRows')
            ->andWhere('collection = command.cartCollection')
            ->andWhere('p.refModel LIKE :text OR p.name LIKE :text OR p.tertiaryCategory LIKE :text')
            ->setParameters(array('text' => '%'.$text.'%',
                'command_id' => $command));
        return $QueryBuilder->getQuery()->getResult();
    }
}