<?php

namespace B2bBundle\Repository;

/**
 * CollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectionRepository extends \Doctrine\ORM\EntityRepository {
    public function findFor($brand) {
        $QueryBuilder = $this->createQueryBuilder('c')
            ->innerJoin('c.season', 's')
            ->where('c.brand = :brand_id')
            ->setParameters(array('brand_id' => $brand))
            ->orderBy('c.year', 'DESC')
            ->addOrderBy('s.rank', 'DESC');
        return $QueryBuilder->getQuery()->getResult();
    }
}
