<?php

namespace B2bBundle\Repository;

/**
 * CommandLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandLineRepository extends \Doctrine\ORM\EntityRepository
{
}
