<?php

namespace B2bBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends EntityRepository {
    public function findInvoices($brand) {
        $QueryBuilder = $this->createQueryBuilder('i')
            ->innerJoin('i.command', 'com')
            ->innerJoin('com.cartCollection', 'cartCollection')
            ->where('cartCollection.brand = :brand_id')
            ->andWhere('i.status <> \'verification\'')
            ->setParameters(array('brand_id' => $brand))
            ->orderBy('i.date', 'DESC');
        return $QueryBuilder->getQuery()->getResult();
    }

    public function findReminded() {
        $QueryBuilder = $this->createQueryBuilder('i')
            ->where('i.status = \'reminder_1\' OR i.status = \'reminder_2\' OR i.status = \'reminder_3\'')
            ->orderBy('i.status', 'DESC');
        return $QueryBuilder->getQuery()->getResult();
    }
}
