<?php

namespace B2bBundle\Repository;
use Doctrine\ORM\QueryBuilder;

/**
 * PaymentMethodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentMethodRepository extends \Doctrine\ORM\EntityRepository {
    public function queryIn($ids) {
        $QueryBuilder = $this->createQueryBuilder('pm')
            ->where('pm.id IN (:ids)')
            ->setParameters(array('ids' => $ids));
        return $QueryBuilder;
    }
}
