<?php

namespace B2bBundle\Repository;

/**
 * PaymentTermsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentTermsRepository extends \Doctrine\ORM\EntityRepository {
    public function queryIn($ids) {
        $QueryBuilder = $this->createQueryBuilder('pt')
            ->where('pt.id IN (:ids)')
            ->setParameters(array('ids' => $ids));
        return $QueryBuilder;
    }
}
