<?php

namespace B2bBundle\Repository;

/**
 * PrimaryCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrimaryCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
