<?php

namespace B2bBundle\Repository;

/**
 * RecommandationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecommandationRepository extends \Doctrine\ORM\EntityRepository
{
}
