<?php

namespace B2bBundle\Repository;
use B2bBundle\Entity\Salesman;
use Doctrine\ORM\EntityRepository;

/**
 * SalesmanShopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesmanShopRepository extends EntityRepository {
}
