<?php

namespace B2bBundle\Repository;

/**
 * SecondaryCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecondaryCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
