<?php

namespace B2bBundle\Repository;

/**
 * SizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SizeQuantityRepository extends \Doctrine\ORM\EntityRepository {
    public function findSizeQuantitiesOrdered($ids) {
        return $this->createQueryBuilder('s')
            ->where('s.id in :ids')
            ->setParameter('ids', $ids)
            ->innerjoin('s.size', 'size')
            ->orderBy('size.rank', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
