backoffice_color_index:
    path:     /
    defaults: { _controller: "B2bBundle:Color:index" }
    methods:  GET

backoffice_color_show:
    path:     /{id}/show
    defaults: { _controller: "B2bBundle:Color:show" }
    methods:  GET

backoffice_color_new:
    path:     /new
    defaults: { _controller: "B2bBundle:Color:new" }
    methods:  [GET, POST]

backoffice_color_edit:
    path:     /{id}/edit
    defaults: { _controller: "B2bBundle:Color:edit" }
    methods:  [GET, POST]

backoffice_color_delete:
    path:     /{id}/delete
    defaults: { _controller: "B2bBundle:Color:delete" }
    methods:  DELETE
