backoffice_contact_index:
    path:     /
    defaults: { _controller: "B2bBundle:Contact:index" }
    methods:  GET

backoffice_contact_show:
    path:     /{id}/show
    defaults: { _controller: "B2bBundle:Contact:show" }
    methods:  GET

backoffice_contact_new:
    path:     /new
    defaults: { _controller: "B2bBundle:Contact:new" }
    methods:  [GET, POST]

backoffice_contact_edit:
    path:     /{id}/edit
    defaults: { _controller: "B2bBundle:Contact:edit" }
    methods:  [GET, POST]

backoffice_contact_delete:
    path:     /{id}/delete
    defaults: { _controller: "B2bBundle:Contact:delete" }
    methods:  DELETE
