backoffice_country_index:
    path:     /
    defaults: { _controller: "B2bBundle:Country:index" }
    methods:  GET

backoffice_country_show:
    path:     /{id}/show
    defaults: { _controller: "B2bBundle:Country:show" }
    methods:  GET

backoffice_country_new:
    path:     /new
    defaults: { _controller: "B2bBundle:Country:new" }
    methods:  [GET, POST]

backoffice_country_edit:
    path:     /{id}/edit
    defaults: { _controller: "B2bBundle:Country:edit" }
    methods:  [GET, POST]

backoffice_country_delete:
    path:     /{id}/delete
    defaults: { _controller: "B2bBundle:Country:delete" }
    methods:  DELETE
