backoffice_size_index:
    path:     /
    defaults: { _controller: "B2bBundle:Size:index" }
    methods:  GET

backoffice_size_show:
    path:     /{id}/show
    defaults: { _controller: "B2bBundle:Size:show" }
    methods:  GET

backoffice_size_new:
    path:     /new
    defaults: { _controller: "B2bBundle:Size:new" }
    methods:  [GET, POST]

backoffice_size_edit:
    path:     /{id}/edit
    defaults: { _controller: "B2bBundle:Size:edit" }
    methods:  [GET, POST]

backoffice_size_delete:
    path:     /{id}/delete
    defaults: { _controller: "B2bBundle:Size:delete" }
    methods:  DELETE
