backoffice_style_index:
    path:     /
    defaults: { _controller: "B2bBundle:Style:index" }
    methods:  GET

backoffice_style_show:
    path:     /{id}/show
    defaults: { _controller: "B2bBundle:Style:show" }
    methods:  GET

backoffice_style_new:
    path:     /new
    defaults: { _controller: "B2bBundle:Style:new" }
    methods:  [GET, POST]

backoffice_style_edit:
    path:     /{id}/edit
    defaults: { _controller: "B2bBundle:Style:edit" }
    methods:  [GET, POST]

backoffice_style_delete:
    path:     /{id}/delete
    defaults: { _controller: "B2bBundle:Style:delete" }
    methods:  DELETE
