backoffice_user_index:
    path:     /
    defaults: { _controller: "B2bBundle:User:index" }
    methods:  GET

backoffice_user_show:
    path:     /{id}/show
    defaults: { _controller: "B2bBundle:User:show" }
    methods:  GET

backoffice_user_new:
    path:     /new
    defaults: { _controller: "B2bBundle:User:new" }
    methods:  [GET, POST]

backoffice_user_edit:
    path:     /{id}/edit
    defaults: { _controller: "B2bBundle:User:edit" }
    methods:  [GET, POST]

backoffice_user_delete:
    path:     /{id}/delete
    defaults: { _controller: "B2bBundle:User:delete" }
    methods:  DELETE
